[metadata]
name = ggblab
version = 1.7.0
description = A JupyterLab extension for GeoGebra-integrated learning
license_file = ../LICENSE

[options]
packages = find:
include_package_data = True
zip_safe = False

[options.package_data]
ggblab =
    labextension/*
    labextension/**/*
    schema/*
    style/*
