
title: ggblab Blog
theme: minima
baseurl: "/ggblab" # site is served under /ggblab on GitHub Pages
url: "https://moyhig-ecs.github.io"  # site URL (without baseurl)

# Keep collections simple; use default posts folder
markdown: kramdown
