name: python 3.14
dependencies:
  - python=3.14
  - matplotlib
  - numpy
  - networkx
  - pandas
  - polars
  - sympy
  - scipy
  - scikit-learn
  - seaborn
  - nbgitpuller
  - lxml
  - xlrd
  - jupyterlab>=4.5
  - jupyterlab-myst
  - jupytext
  - openai
  - langchain
  - langchain-openai
  - webio-jupyter-extension
  - pip
  - pip:
      - julia
      - juliacall
      - ggblab
      - japanize-matplotlib
