name: python 3.14
dependencies:
  - python=3.14
  - matplotlib
  - numpy
  - networkx
  - pandas
  - polars
  - sympy
  - scipy
  - scikit-learn
  - seaborn
  - nbgitpuller
  - lxml
  - xlrd
  - jupyterlab>=4.5
  - jupyterlab-myst
  - jupytext
# - openai
# - langchain
# - langchain-openai
# for ggblab
  - websockets
  - ipylab
  - aiofiles
  - xmlschema
  - networkx
  - ipykernel
  - pyperclip
  - psutil
  - pip
  - pip:
      - julia
      - juliacall
      - ggblab
      - japanize-matplotlib
      - https://github.com/moyhig-ecs/WebIO.jl/releases/download/v0.8.21/webio_jupyter_extension-0.1.0-py3-none-any.whl
